import { getInstrument, SDOH30_QUESTIONS } from './instruments.js'
import { GC_DOMAIN_LABELS, GC_DOMAIN_WEIGHTS, SDOH6_DOMAIN_MAP, type GCDomainCode } from '../scoring/givecareScore.js'

/**
 * The shared, machine-readable projection of the public SDOH instruments.
 *
 * gc-tools owns the instrument definition. This snapshot is the canonical
 * artifact downstream copies gate against:
 *   - `gc-evals` syncs its exact bytes before adding local packaging metadata.
 *   - `gc-sms` syncs its exact bytes without redefining questions.
 *
 * Only the fields that must not silently drift live here: instrument ids,
 * question ids + prompts, per-question GC domains (where defined), and the
 * structural composite weights. Human-facing packaging copy (titles,
 * descriptions, cadence, license notes, band labels) stays in the gc-evals
 * distribution record, not in the code definition.
 */
export interface ExportedQuestion {
  readonly id: string
  readonly prompt: string
  /** Present for domain-anchored instruments; EMA-3 is a separate reading. */
  readonly gcDomain?: GCDomainCode
}

export interface InstrumentExport {
  readonly note: string
  readonly version: string
  readonly instruments: {
    readonly gc_sdoh6: readonly ExportedQuestion[]
    readonly ema3: readonly ExportedQuestion[]
    readonly gc_sdoh30: readonly ExportedQuestion[]
  }
  readonly domainWeights: Readonly<Record<GCDomainCode, number>>
  readonly domainLabels: Readonly<Record<GCDomainCode, string>>
}

const EXPORT_NOTE =
  'Canonical shared SDOH instrument definition, generated by ' +
  'scripts/project-instruments.ts from src/assessments/instruments.ts (@givecare/tools). ' +
  'gc-tools owns this definition; downstream copies (gc-evals distribution records, ' +
  'gc-sms production runtime) gate against it. Do not hand-edit — rerun the owner projection script.'

/** Build the deterministic shared-instrument snapshot from the source of truth. */
export function buildInstrumentExport(): InstrumentExport {
  const gcSdoh6: ExportedQuestion[] = getInstrument('gc_sdoh6').questions.map(q => ({
    id: q.id,
    prompt: q.prompt,
    gcDomain: SDOH6_DOMAIN_MAP[q.id],
  }))
  const ema3: ExportedQuestion[] = getInstrument('ema3').questions.map(q => ({
    id: q.id,
    prompt: q.prompt,
  }))
  const gcSdoh30: ExportedQuestion[] = SDOH30_QUESTIONS.map(q => ({
    id: q.id,
    prompt: q.prompt,
    gcDomain: q.gcDomain,
  }))

  return {
    note: EXPORT_NOTE,
    version: getInstrument('gc_sdoh6').version,
    instruments: { gc_sdoh6: gcSdoh6, ema3, gc_sdoh30: gcSdoh30 },
    domainWeights: GC_DOMAIN_WEIGHTS,
    domainLabels: GC_DOMAIN_LABELS,
  }
}
